### ISSUE TITLE
Improve readme description with animated gifs

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camel-extension-pack#18]
which scenario to show exactly?

proposal:
- one gif to create a camel project using project initializer
- one to launch test from inlined java code --> it is not visual enough with just a gif
- one with Camel URI completion
- one with "watch" to an OpenShift instance  --> it is not visual enough with just a gif
- one for the wsdl2rest

**Comment by tsedmik** [comment]
verified with master branch
