### ISSUE TITLE
Move to Red Hat publisher

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camel-extension-pack#22]
- remove publish from Travis config
- change icon
- change publisher in package.json
- provide jenkins pipeline config

see also https://github.com/camel-tooling/camel-lsp-client-vscode/issues/107

**Comment by apupier** [comment]
would like to have the ftp using a better place for dwonload;jboss;org before closing.
currently in 
https://download.jboss.org/jbosstools/snapshots/
and release inside https://download.jboss.org/jbosstools/stable/

would be best in https://download.jboss.org/jbosstools/vscode/snapshots/
and release inside https://download.jboss.org/jbosstools/vscode/stable/ but requires to create the vscode folder on the server (and I don't have rights, waiting to have answers on who can do that)

**Comment by djelinek** [comment]
verified with master branch
